version: '3.9'

services:

  db:
    image: asteurer/resume_api_database
    restart: always
    container_name: db
    # set shared memory limit
    shm_size: 128mb
    volumes:
      # This is the path to the EBS volume
      - type: bind
        source: /mnt/pgdata/pg_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_HOST}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5433:5432
    build:
      context: ./

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    ports:
      - "5000:5000"
    build:
      context: ./app
    image: asteurer/resume_api_app
    restart: always
    container_name: app
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: db
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD} 
      VALID_TOKEN: ${VALID_TOKEN}
    depends_on:
      - db

volumes:
  pgdata: